version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: magento-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: magento-mailhog
      ports:
        - "8061:8025"

    redis:
      image: redis:alpine
      container_name: magento-redis

    mysql:
      image: mysql:5.7
      container_name: magento-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8062:3306"

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: magento-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: magento-webserver
      restart: unless-stopped
      working_dir: /application
      volumes:
          - ./data/nginx:/etc/nginx/conf.d
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
       - "443:443"
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
      image: certbot/certbot
      container_name: magento-certbot
      restart: unless-stopped
      volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
        - .:/application
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: magento-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

